import { Table } from "@radix-ui/themes";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

/**
 * ref: https://dev.to/gugaguichard/replace-clsx-classnames-or-classcat-with-your-own-little-helper-3bf#comment-26077
 */
export function cn(
  ...args: Array<undefined | null | string | boolean>
): string {
  return args
    .flat()
    .filter((x) => typeof x === "string")
    .join(" ");
}

export default function Home() {
  const { data: facts } = api.factool.getAll.useQuery();
  console.log({ facts });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={cn(
          "flex min-h-screen flex-col items-center justify-center bg-gradient-to-b ",
          // "from-[#2e026d] to-[#15162c]"
        )}
      >
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1
            className={cn(
              "text-4xl font-extrabold tracking-tight sm:text-[5rem]",
              // "text-white"
            )}
          >
            大模型评测
          </h1>
          <p
            className={cn()
            // " tracking-tight sm:text-[5rem]",
            // "text-white"
            }
          >
            based on
            [ChineseFactEval](https://gair-nlp.github.io/ChineseFactEval/)
          </p>

          <Table.Root>
            <Table.Header>
              <Table.Row>
                <Table.ColumnHeaderCell>prompt</Table.ColumnHeaderCell>
                <Table.ColumnHeaderCell>category</Table.ColumnHeaderCell>
                <Table.ColumnHeaderCell>weight</Table.ColumnHeaderCell>
                <Table.ColumnHeaderCell>response</Table.ColumnHeaderCell>
              </Table.Row>
            </Table.Header>

            <Table.Body>
              {(facts ?? []).map((line, index) => (
                <Table.Row key={index}>
                  <Table.RowHeaderCell>{line.prompt}</Table.RowHeaderCell>
                  <Table.Cell>{line.category}</Table.Cell>
                  <Table.Cell>{line.weight}</Table.Cell>
                  <Table.Cell>{"[]"}</Table.Cell>
                </Table.Row>
              ))}
            </Table.Body>
          </Table.Root>
        </div>
      </main>
    </>
  );
}
